import React from 'react';
import Head from 'next/head';
import BaseLayout from '../components/layouts/BaseLayout';
import 'styles/globals.scss'

export interface AppPropsType {
  Component: any;
  pageProps: any;
}

const App: React.FC<AppPropsType> = ({ Component, pageProps }) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <Component {...pageProps} />
      </BaseLayout>
    </>
  )
}

export default App;
